#!/usr/bin/env python3
"""
Fetch GitHub pull request metrics (cycle time and LOC) for one or more repositories.

The script produces raw and aggregated CSV exports and renders summary charts
covering the last N weeks (26 by default).

Example usage:
    export GITHUB_TOKEN=ghp_yourtoken
    python fetch_metrics.py --repos org/repo1 org/repo2 --weeks 26 --output ./metrics

The token only requires the `repo` scope for private repositories or can be an
`GITHUB_TOKEN` generated by GitHub Actions. The script uses the GitHub REST API
and respects the rate limit by pausing when necessary.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import os
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional

import math
import textwrap

try:
    import matplotlib.pyplot as plt  # type: ignore
    HAS_MATPLOTLIB = True
except Exception:  # pragma: no cover - optional dependency
    HAS_MATPLOTLIB = False

import requests

API_URL = "https://api.github.com"
REQUESTS_TIMEOUT = 30


@dataclass
class PullRequestRecord:
    repo: str
    number: int
    title: str
    author: str
    created_at: dt.datetime
    merged_at: dt.datetime
    additions: int
    deletions: int

    @property
    def cycle_time_hours(self) -> float:
        delta = self.merged_at - self.created_at
        return delta.total_seconds() / 3600.0

    @property
    def week_start(self) -> dt.date:
        """Return the ISO week start (Monday) for `merged_at`."""
        merged_date = self.merged_at.date()
        return merged_date - dt.timedelta(days=merged_date.weekday())


class GitHubClient:
    def __init__(self, token: str) -> None:
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "github-metrics-script",
        })

    def _request(self, method: str, url: str, params: Optional[Dict[str, str]] = None) -> requests.Response:
        while True:
            response = self.session.request(method, url, params=params, timeout=REQUESTS_TIMEOUT)
            if response.status_code == 403 and "rate limit" in response.text.lower():
                reset = response.headers.get("X-RateLimit-Reset")
                if reset is not None:
                    reset_time = dt.datetime.fromtimestamp(int(reset), tz=dt.timezone.utc)
                    sleep_for = max((reset_time - dt.datetime.now(dt.timezone.utc)).total_seconds(), 1)
                    print(f"Rate limit reached. Sleeping for {sleep_for:.0f} seconds until reset…", file=sys.stderr)
                    time.sleep(sleep_for)
                    continue
            response.raise_for_status()
            return response

    def iterate_pull_requests(self, repo: str, since: dt.datetime) -> Iterable[Dict]:
        page = 1
        while True:
            params = {
                "state": "closed",
                "per_page": "100",
                "page": str(page),
                "sort": "updated",
                "direction": "desc",
            }
            url = f"{API_URL}/repos/{repo}/pulls"
            response = self._request("GET", url, params=params)
            pulls = response.json()
            if not pulls:
                break
            for pr in pulls:
                merged_at = pr.get("merged_at")
                if not merged_at:
                    continue
                merged_dt = dt.datetime.fromisoformat(merged_at.replace("Z", "+00:00"))
                if merged_dt < since:
                    return
                yield pr
            page += 1

    def fetch_pull_request_details(self, repo: str, number: int) -> Dict:
        url = f"{API_URL}/repos/{repo}/pulls/{number}"
        response = self._request("GET", url)
        return response.json()


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate weekly GitHub PR metrics (cycle time & LOC).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """
            The script generates the following files:
              * raw_pull_requests.csv – one row per merged PR
              * weekly_aggregate.csv – team metrics grouped by week
              * weekly_by_author.csv – metrics grouped by author and week
              * charts/*.png – charts summarising the aggregates (if matplotlib is available)
            """
        ),
    )
    parser.add_argument(
        "--repos",
        nargs="+",
        required=True,
        help="List of repositories in the form owner/name",
    )
    parser.add_argument(
        "--weeks",
        type=int,
        default=26,
        help="Number of weeks in the look-back window (default: 26)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("metrics_output"),
        help="Directory where CSV files and charts will be written",
    )
    return parser.parse_args(argv)


def ensure_token() -> str:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise SystemExit("GITHUB_TOKEN environment variable is required")
    return token


def fetch_records(client: GitHubClient, repos: List[str], weeks: int) -> List[PullRequestRecord]:
    cutoff = dt.datetime.now(dt.timezone.utc) - dt.timedelta(weeks=weeks)
    records: List[PullRequestRecord] = []
    for repo in repos:
        print(f"Fetching PRs for {repo}…", file=sys.stderr)
        for pr in client.iterate_pull_requests(repo, cutoff):
            details = client.fetch_pull_request_details(repo, pr["number"])
            merged_at = details.get("merged_at")
            created_at = details.get("created_at")
            if not merged_at or not created_at:
                continue
            record = PullRequestRecord(
                repo=repo,
                number=details["number"],
                title=details.get("title", ""),
                author=(details.get("user") or {}).get("login", "unknown"),
                created_at=dt.datetime.fromisoformat(created_at.replace("Z", "+00:00")),
                merged_at=dt.datetime.fromisoformat(merged_at.replace("Z", "+00:00")),
                additions=details.get("additions", 0),
                deletions=details.get("deletions", 0),
            )
            if record.merged_at < cutoff:
                continue
            records.append(record)
    records.sort(key=lambda r: r.merged_at)
    return records


def write_raw_csv(records: List[PullRequestRecord], output_dir: Path) -> Path:
    path = output_dir / "raw_pull_requests.csv"
    with path.open("w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow([
            "repo",
            "number",
            "title",
            "author",
            "created_at",
            "merged_at",
            "cycle_time_hours",
            "additions",
            "deletions",
        ])
        for record in records:
            writer.writerow([
                record.repo,
                record.number,
                record.title,
                record.author,
                record.created_at.isoformat(),
                record.merged_at.isoformat(),
                f"{record.cycle_time_hours:.2f}",
                record.additions,
                record.deletions,
            ])
    return path


def aggregate_weekly(records: List[PullRequestRecord]) -> Dict[dt.date, Dict[str, float]]:
    weekly: Dict[dt.date, Dict[str, float]] = defaultdict(lambda: defaultdict(float))
    counts: Dict[dt.date, int] = defaultdict(int)

    for record in records:
        week = record.week_start
        weekly[week]["total_cycle_time"] += record.cycle_time_hours
        weekly[week]["additions"] += record.additions
        weekly[week]["deletions"] += record.deletions
        counts[week] += 1

    for week, metrics in weekly.items():
        count = counts[week]
        metrics["pr_count"] = count
        metrics["avg_cycle_time"] = metrics["total_cycle_time"] / count if count else math.nan
    return weekly


def aggregate_weekly_by_author(records: List[PullRequestRecord]) -> Dict[str, Dict[dt.date, Dict[str, float]]]:
    result: Dict[str, Dict[dt.date, Dict[str, float]]] = defaultdict(lambda: defaultdict(lambda: defaultdict(float)))
    counts: Dict[str, Dict[dt.date, int]] = defaultdict(lambda: defaultdict(int))

    for record in records:
        week = record.week_start
        author = record.author or "unknown"
        metrics = result[author][week]
        metrics["total_cycle_time"] += record.cycle_time_hours
        metrics["additions"] += record.additions
        metrics["deletions"] += record.deletions
        counts[author][week] += 1

    for author, weeks in result.items():
        for week, metrics in weeks.items():
            count = counts[author][week]
            metrics["pr_count"] = count
            metrics["avg_cycle_time"] = metrics["total_cycle_time"] / count if count else math.nan
    return result


def write_weekly_csv(weekly: Dict[dt.date, Dict[str, float]], output_dir: Path) -> Path:
    path = output_dir / "weekly_aggregate.csv"
    with path.open("w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["week_start", "pr_count", "avg_cycle_time_hours", "total_additions", "total_deletions"])
        for week in sorted(weekly):
            metrics = weekly[week]
            avg_cycle = metrics.get("avg_cycle_time", math.nan)
            writer.writerow([
                week.isoformat(),
                int(metrics.get("pr_count", 0)),
                f"{avg_cycle:.2f}" if avg_cycle == avg_cycle else "nan",
                int(metrics.get("additions", 0)),
                int(metrics.get("deletions", 0)),
            ])
    return path


def write_weekly_by_author_csv(by_author: Dict[str, Dict[dt.date, Dict[str, float]]], output_dir: Path) -> Path:
    path = output_dir / "weekly_by_author.csv"
    with path.open("w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow([
            "author",
            "week_start",
            "pr_count",
            "avg_cycle_time_hours",
            "total_additions",
            "total_deletions",
        ])
        for author in sorted(by_author):
            weeks = by_author[author]
            for week in sorted(weeks):
                metrics = weeks[week]
                avg_cycle = metrics.get("avg_cycle_time", math.nan)
                writer.writerow([
                    author,
                    week.isoformat(),
                    int(metrics.get("pr_count", 0)),
                    f"{avg_cycle:.2f}" if avg_cycle == avg_cycle else "nan",
                    int(metrics.get("additions", 0)),
                    int(metrics.get("deletions", 0)),
                ])
    return path


def render_charts(weekly: Dict[dt.date, Dict[str, float]], by_author: Dict[str, Dict[dt.date, Dict[str, float]]], output_dir: Path) -> None:
    if not HAS_MATPLOTLIB:
        print("matplotlib not available – skipping chart generation", file=sys.stderr)
        return

    charts_dir = output_dir / "charts"
    charts_dir.mkdir(exist_ok=True)

    weeks = sorted(weekly)
    if weeks:
        avg_cycle = [weekly[w].get("avg_cycle_time", math.nan) for w in weeks]
        additions = [weekly[w].get("additions", 0) for w in weeks]
        deletions = [weekly[w].get("deletions", 0) for w in weeks]

        plt.figure(figsize=(10, 5))
        plt.plot(weeks, avg_cycle, marker="o")
        plt.title("Average PR Cycle Time by Week")
        plt.ylabel("Hours")
        plt.xlabel("Week starting")
        plt.grid(True, linestyle=":", linewidth=0.5)
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.savefig(charts_dir / "team_avg_cycle_time.png")
        plt.close()

        plt.figure(figsize=(10, 5))
        plt.plot(weeks, additions, marker="o", label="Additions")
        plt.plot(weeks, deletions, marker="o", label="Deletions")
        plt.title("Total LOC Changes by Week")
        plt.ylabel("Lines")
        plt.xlabel("Week starting")
        plt.legend()
        plt.grid(True, linestyle=":", linewidth=0.5)
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.savefig(charts_dir / "team_loc.png")
        plt.close()

    # Individual charts: limit to top 5 authors by PR count to keep charts readable.
    author_totals = [
        (author, sum(weeks[week].get("pr_count", 0) for week in weeks))
        for author, weeks in by_author.items()
    ]
    top_authors = {author for author, _ in sorted(author_totals, key=lambda x: x[1], reverse=True)[:5]}

    for author in sorted(top_authors):
        weeks = sorted(by_author[author])
        if not weeks:
            continue
        avg_cycle = [by_author[author][w].get("avg_cycle_time", math.nan) for w in weeks]
        additions = [by_author[author][w].get("additions", 0) for w in weeks]
        deletions = [by_author[author][w].get("deletions", 0) for w in weeks]

        plt.figure(figsize=(10, 5))
        plt.plot(weeks, avg_cycle, marker="o")
        plt.title(f"Average Cycle Time – {author}")
        plt.ylabel("Hours")
        plt.xlabel("Week starting")
        plt.grid(True, linestyle=":", linewidth=0.5)
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.savefig(charts_dir / f"{author}_avg_cycle_time.png")
        plt.close()

        plt.figure(figsize=(10, 5))
        plt.plot(weeks, additions, marker="o", label="Additions")
        plt.plot(weeks, deletions, marker="o", label="Deletions")
        plt.title(f"LOC Changes – {author}")
        plt.ylabel("Lines")
        plt.xlabel("Week starting")
        plt.legend()
        plt.grid(True, linestyle=":", linewidth=0.5)
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.savefig(charts_dir / f"{author}_loc.png")
        plt.close()



def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    token = ensure_token()
    output_dir: Path = args.output
    output_dir.mkdir(parents=True, exist_ok=True)

    client = GitHubClient(token)
    records = fetch_records(client, args.repos, args.weeks)
    if not records:
        print("No merged pull requests found in the specified window.")
        return 0

    write_raw_csv(records, output_dir)
    weekly = aggregate_weekly(records)
    write_weekly_csv(weekly, output_dir)
    by_author = aggregate_weekly_by_author(records)
    write_weekly_by_author_csv(by_author, output_dir)
    render_charts(weekly, by_author, output_dir)
    print(f"Wrote metrics to {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
